### PR TITLE
PP-12001/cxx17 support

### PR DESCRIPTION
**Pull request by BenFrantzDale**

### CODE REVIEW

**Comment by balintfodor** [comment]
Shouldn't we force upgrading to the latest stable catch2 instead of tweaking in our fork? I know we had problems with a newer catch2 but I think we should keep our public forks clean especially if the fix is already in upstream. https://github.com/catchorg/Catch2/search?q=auto_ptr&unscoped_q=auto_ptr

**Comment by djkazic** [comment]
@balintfodor it was a nightmare upgrading to Catch2. You can have a shot at it if you want, but last time Ben and I spent a few hours and had to really really hack at it to get it to even compile.

**Comment by djkazic** [comment]
Catch2 is considered pretty much a rewrite, so it doesn't surprise me that it doesn't just work as a drop-in replacement.

**Review by djkazic — APPROVED** [review]

**Comment by andmis** [comment]
@balintfodor holding down the fort!

**Comment by djkazic** [comment]
Once Catch hits official End of Life we can revisit the Catch2 upgrade.

**Comment by balintfodor** [comment]
Can I close this?

**Pull request closed without merging**
